version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    commit_message:
      prefix: "chore(deps)"
      include_scope: false
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
